name: deep_fuse
version: 0.1.0
description: >
  web server for neural style
author: rinick <rinick@gmail.com>
homepage: https://github.com/rinick/deep-fuse

dependencies:
  browser: ^0.10.0
  mime: ^0.9.3
  http_server: ^0.9.6
transformers:
- $dart2js:
    commandLineOptions: [--no-frequency-based-minification]